{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <pytest_demo.test_allure.TestAllure object at 0x10f829278>\n\n    @allure.story(\"测试失败\")\n    def test_failure(self):\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure.py:13: AssertionError"}, "description": "this test fails", "start": 1594115079579, "stop": 1594115079579, "uuid": "5546e1d3-60ef-4af9-945b-074f3f1894bf", "historyId": "08c4ffe11fcd35938b73fd0f4c7e3cc1", "testCaseId": "c2458f065f1c6022e2e6216543d38c0b", "fullName": "test_allure.TestAllure#test_failure", "labels": [{"name": "story", "value": "测试失败"}, {"name": "feature", "value": "测试样例"}, {"name": "suite", "value": "test_allure"}, {"name": "subSuite", "value": "TestAllure"}, {"name": "host", "value": "heweimaodeMacBook-Pro.local"}, {"name": "thread", "value": "61586-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}